# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4b781021cd49512b624427367cb9215a3c705f2cca089a5e96ced22b63214f1b4fac6eec10ab310bf99406f9e3b9b30698c0c82aee832da41fcefd16eeec74b

test:
  secret_key_base: 968a68e96a8a8be955887c893b07480cf2ca8f59875d9d78ca7b5d7d203325576f42513f321b7dad34d106e33b93d6cf9540c8516316e41d10d0a1b2fa2c1f7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
